version: "3.7"

services:
  painel-evo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:7oqmxlmreoak@postgres:5432/dbevolution
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - PORT=3000
      - FRONTEND_URL=https://painel-evo.advancedbot.com.br
      - EVOLUTION_WEBHOOK_SECRET=${EVOLUTION_WEBHOOK_SECRET:-webhook-secret}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-}
      - NODE_ENV=production
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.painel-evo-api.rule=Host(`painel-evo.advancedbot.com.br`) && PathPrefix(`/api`)"
        - "traefik.http.routers.painel-evo-api.entrypoints=websecure"
        - "traefik.http.routers.painel-evo-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.painel-evo-api.loadbalancer.server.port=3000"
        - "traefik.docker.network=network_public"
    depends_on:
      - postgres

  painel-evo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.painel-evo-web.rule=Host(`painel-evo.advancedbot.com.br`)"
        - "traefik.http.routers.painel-evo-web.entrypoints=websecure"
        - "traefik.http.routers.painel-evo-web.tls.certresolver=letsencrypt"
        - "traefik.http.services.painel-evo-web.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"

  # Referência ao PostgreSQL existente (não será criado, apenas referenciado)
  postgres:
    image: postgres:16.0
    external_links:
      - postgres:postgres
    networks:
      - network_public

networks:
  network_public:
    external: true
    name: network_public